### ISSUE TITLE
Benchmark submission: v2.2.3 test results

### ISSUE THREAD

**Issue by saravan2** [iocost-benchmark/iocost-benchmarks#28]
[resctl-bench-result_2022_07_01-00_26_38.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9155631/resctl-bench-result_2022_07_01-00_26_38.json.gz)
[resctl-bench-result_2022_07_01-00_35_36.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9155633/resctl-bench-result_2022_07_01-00_35_36.json.gz)
[resctl-bench-result_2022_07_05-23_50_43.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9155634/resctl-bench-result_2022_07_05-23_50_43.json.gz)
[resctl-bench-result_2022_07_11-23_37_51.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9155635/resctl-bench-result_2022_07_11-23_37_51.json.gz)
[resctl-bench-result_2022_06_29-22_00_21.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9155636/resctl-bench-result_2022_06_29-22_00_21.json.gz)
[resctl-bench-result_2022_07_05-23_48_03.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9155640/resctl-bench-result_2022_07_05-23_48_03.json.gz)
[resctl-bench-result_2022_07_06-00_00_45.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9155647/resctl-bench-result_2022_07_06-00_00_45.json.gz)
[resctl-bench-result_2022_06_29-22_06_34.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9155649/resctl-bench-result_2022_06_29-22_06_34.json.gz)
[resctl-bench-result_2022_06_29-21_53_40.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9155652/resctl-bench-result_2022_06_29-21_53_40.json.gz)
[resctl-bench-result_2022_07_01-00_25_25.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9155653/resctl-bench-result_2022_07_01-00_25_25.json.gz)

**Comment by kov** [comment]
This ran properly after a fix to a bug I had added to resctl-bench.
