### ISSUE TITLE
Benchmark submission: v2.2.3 

### ISSUE THREAD

**Issue by saravan2** [iocost-benchmark/iocost-benchmarks#33]
[resctl-bench-result_2022_07_22-23_59_33.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9237893/resctl-bench-result_2022_07_22-23_59_33.json.gz)
[resctl-bench-result_2022_07_22-23_50_15.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9237895/resctl-bench-result_2022_07_22-23_50_15.json.gz)
[resctl-bench-result_2022_07_26-01_30_47.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9237896/resctl-bench-result_2022_07_26-01_30_47.json.gz)
[resctl-bench-result_2022_07_26-19_38_06.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9237899/resctl-bench-result_2022_07_26-19_38_06.json.gz)
[resctl-bench-result_2022_07_26-01_42_16.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9237900/resctl-bench-result_2022_07_26-01_42_16.json.gz)
[resctl-bench-result_2022_07_22-23_47_42.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9237903/resctl-bench-result_2022_07_22-23_47_42.json.gz)
[resctl-bench-result_2022_07_26-01_30_15.json.gz](https://github.com/iocost-benchmark/iocost-benchmarks/files/9237906/resctl-bench-result_2022_07_26-01_30_15.json.gz)

**Comment by kov** [comment]
@saravan2 can you check the output here:

https://github.com/iocost-benchmark/iocost-benchmarks/actions/runs/2819822797
