### ISSUE TITLE
Metadata files have a double dot in the name

### ISSUE THREAD

**Issue by keszybz** [iocost-benchmark/iocost-benchmarks#51]
E.g. `result-160f4730af01d4b2f1bb1c924764ef77.json..metadata`.

**Comment by santoshmahto7** [comment]
This was happening in older metadata filenames and the recent one seems perfect.

**Comment by saravan2** [comment]
@santoshmahto7 Are we going to rename ?

**Comment by santoshmahto7** [comment]
Fixed with this MR https://github.com/iocost-benchmark/iocost-benchmarks/pull/64 (merged).

**Comment by saravan2** [comment]
Merged : https://github.com/iocost-benchmark/iocost-benchmarks/pull/64
