### ISSUE TITLE
How to use this data?

### ISSUE THREAD

**Issue by keszybz** [iocost-benchmark/iocost-benchmarks#52]
I found my drive in the db. But how to go from the 1.6 MB json.gz file to the hwdb entry?

**Comment by keszybz** [comment]
Ah, OK, so something is supposed to be generated somewhere…
But the last workflow is https://github.com/iocost-benchmark/iocost-benchmarks/actions/runs/3638989499 and that is all "expired"?

**Comment by santoshmahto7** [comment]
You need to create a new issue as per the template provided in this repo( just click on new issue and follow ) and the CI will take care of generating new hwdb in artifacts.

Here are some details
To submit an iocost benchmark:

- Update the issue title with some information about the device you are submitting for.
- Attach your benchmark in `.json.gz` format bu dragging & dropping onto this issue.
- Submit issue.
- Await response from the github actions bot!

**Comment by keszybz** [comment]
Sorry, but that's not an answer that is useful for a low-level system component :(

Essentially, we need a way to do the processing on local machines. It also needs to be happen programatically in a way that does not involve network access. I.e. a set of reasonable commands invoked from the command line.

**Comment by santoshmahto7** [comment]
Eventually, this is done by few tools but not sure that can be run independently. I will check and let you know

**Comment by santoshmahto7** [comment]
The standalone benchmark result can be processed to generate hwdb file as :
```
santosharchvm@archlinux iocost]$ resctl-bench --result kxg5-1.json.gz  format iocost-tune:hwdb
block:*:name:Samsung SSD 860:fwrev:*:
  IOCOST_SOLUTIONS=isolation isolated-bandwidth bandwidth naive
  IOCOST_MODEL_ISOLATION=rbps=348757337 rseqiops=57989 rrandiops=60273 wbps=233318819 wseqiops=55425 wrandiops=56147
  IOCOST_QOS_ISOLATION=rpct=0.00 rlat=3076 wpct=0.00 wlat=2550 min=100.00 max=100.00
  IOCOST_MODEL_ISOLATED_BANDWIDTH=rbps=378956936 rseqiops=63010 rrandiops=65492 wbps=253522364 wseqiops=60225 wrandiops=61008
  IOCOST_QOS_ISOLATED_BANDWIDTH=rpct=0.00 rlat=3208 wpct=0.00 wlat=2705 min=100.00 max=100.00
  IOCOST_MODEL_BANDWIDTH=rbps=446557350 rseqiops=74250 rrandiops=77174 wbps=298747072 wseqiops=70968 wrandiops=71891
  IOCOST_QOS_BANDWIDTH=rpct=0.00 rlat=3506 wpct=0.00 wlat=2852 min=100.00 max=100.00
  IOCOST_MODEL_NAIVE=rbps=570226546 rseqiops=94813 rrandiops=98547 wbps=381481821 wseqiops=90622 wrandiops=91801
  IOCOST_QOS_NAIVE=rpct=99.00 rlat=3960 wpct=99.00 wlat=2852 min=75.00 max=100.00
  IOCOST_MODEL_RLAT_99_Q1=rbps=570226546 rseqiops=94813 rrandiops=98547 wbps=381481821 wseqiops=90622 wrandiops=91801
  IOCOST_QOS_RLAT_99_Q1=rpct=99.00 rlat=3960 wpct=0.00 wlat=0 min=82.08 max=100.00
  IOCOST_MODEL_RLAT_99_Q2=rbps=468070460 rseqiops=77827 rrandiops=80892 wbps=313139353 wseqiops=74387 wrandiops=75355
  IOCOST_QOS_RLAT_99_Q2=rpct=99.00 rlat=3600 wpct=0.00 wlat=0 min=82.49 max=100.00
```

Note:  Although this repo process results in corelation with existing result in database directory. i.e it first merges benchmark result with existing data ( database directory) based on model name  then generating hwdb file for each model and then merging all individual hwdb file to generate single final hwdb (90-iocost-tune.hwdb) which can be installed in system.
