### ISSUE TITLE
Result ingestion pipeline fails due to missing pdf generation dependency packages

### ISSUE THREAD

**Issue by htejun** [iocost-benchmark/iocost-benchmarks#66]
Tried to submit result for 980 pro. Didn't work:

https://github.com/iocost-benchmark/iocost-benchmarks/actions/runs/5535315267/jobs/10101438988

**Comment by santoshmahto7** [comment]
This seems to be temporary n/w issue.
Latest trail run succesfully passed 
https://github.com/iocost-benchmark/iocost-benchmarks/actions/runs/5671223788

**Comment by ewyler** [comment]
Can this be closed in that case?
