### ISSUE TITLE
Image is broken

### ISSUE THREAD

**Issue by ewyler** [iocost-benchmark/iocost-benchmarks#82]

**Comment by santoshmahto7** [comment]
Now it's confirmed, the image is using resctl-demo available in [crates.io](https://crates.io/crates/resctl-demo)
So publishing new version in crates.io will solve the broken image problem.
@htejun : I don't seems to have permission to login with organization permission. Could you confirm if you want to do it ?

**Comment by santoshmahto7** [comment]
PR:
1. wait unit boot partition is recognised and also debugging 
  - https://github.com/iocost-benchmark/resctl-demo-image-recipe/pull/39
  
2. Make pivot as default option
 - https://github.com/iocost-benchmark/resctl-demo-image-recipe/pull/40

**Comment by obbardc** [comment]
duplicate of [resctl-demo-image-recipe#](https://github.com/iocost-benchmark/resctl-demo-image-recipe/issues/35)
