### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by ewyler** [iocost-benchmark/iocost-benchmarks#83]

**Comment by santoshmahto7** [comment]
Two PR created to fix this:
1 resctl-demo : https://github.com/facebookexperimental/resctl-demo/pull/304 (Note: new tag v2.1.3 should be created with branch)
 -  Fixes build issue with older version.

2 iocost-benchmark-ci: https://github.com/iocost-benchmark/iocost-benchmarks-ci/pull/22
 - Uses new tag for resctl-demo version 2.1

**Comment by obbardc** [comment]
This will be tracked in issues which will start to describe exactly what is broken.
